//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoreCore.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ElderbugText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElderbugText() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoreCore.Resources.Text.ElderbugText", typeof(ElderbugText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ah, I see that you&apos;ve acquired some more knowledge. Let me reward you for that. ähnelt.
        /// </summary>
        internal static string Enough {
            get {
                return ResourceManager.GetString("Enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oh hello there, wandering around this forsaken land all by your own? Although you seem to already have a destination, may I ask for a favor? Once this was a great kingdom with multiple cultures, with powerful knowledge buried deep inside. Over the years the residents ceased to exist, but their knowledge will stay forever. Explore this place and gather as much knowledge as you can. You will see that certain history bits are a bit... special. On your own, you&apos;d not be able to see their potential, but I&apos;m here [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Introduction1 {
            get {
                return ResourceManager.GetString("Introduction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I&apos;ve marked you as a knowledge guardian, able to absorb the magic behind certain history pieces. Onces you&apos;ve read them, you&apos;ll be able to burn them into your shell notches to unleash their great power. Well... at least when the notches have been unsealed, which I could do. But to put you to the test, I&apos;ll refrain from doing so right now. Start you journey, listen to the leftover residents, read the tablets or other interesting structures scattered around the land and maybe even hear the dreams of the decea [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Introduction2 {
            get {
                return ResourceManager.GetString("Introduction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It seems that you&apos;ve not obtained enough knowledge yet. Come back to me once you a are a little... wiser. ähnelt.
        /// </summary>
        internal static string NotEnough {
            get {
                return ResourceManager.GetString("NotEnough", resourceCulture);
            }
        }
    }
}
